#!/usr/bin/env bash

WORLD=${HOMEBREW_PREFIX}/var/world

list() {
    COLUMNS=1 column $WORLD
}

add() {
    local BREW_LIST=$(brew list)
    for name in "$@"; do
        local full_name=$(brew list --versions $name | awk '{print $1}')
        [ ! -z $full_name ] && [[ $BREW_LIST =~ ${full_name}([[:space:]]|$) ]] && echo $full_name >> $WORLD
    done
    sort -uo $WORLD $WORLD
}

delete() {
    for name in "$@"; do
        local full_name=$(brew info $name 2>&1 | head -1 | grep -v Error | awk -F: '{print $1}'| sed -E 's/.*\/(.*)/\1/')
        [ ! -z $full_name ] && sed -i~ "/^${full_name}$/d" $WORLD
    done
    rm -f $WORLD~
}

install() {
    brew install "$@" && add "$@"
}

uninstall() {
    brew uninstall "$@" && delete "$@" && clean
}

clean() {
    local ORPHANS=$(diff $WORLD <(brew leaves | sed -E 's/.*\/(.*)/\1/') | awk '/^>/{print $2}')
    if [ ! -z "$ORPHANS" ]; then
        brew uninstall $(echo -n $ORPHANS) && clean
    fi
}

create() {
    if [ -s $WORLD ]; then
        echo -n 'The world already exists, do you want to keep it? [Y/n] '
        read answer
        [[ $answer =~ ^[Nn]$ ]] && : > $WORLD
    fi
    echo 'Scanning for installed formulae...'
    for formula in $(diff $WORLD <(brew list) | awk '/^>/{print $2}'); do
        local parent_formulae=$(brew uses --installed $formula)
        if [[ ! -z $parent_formulae ]]; then
            echo -e "\x1B[1;32m${formula}\x1B[0m is automatically installed by"
            for parent_formula in $parent_formulae; do
                echo -e "  - \x1B[1m${parent_formula}\x1B[0m"
            done
        fi
        echo -en "Do you want to add \x1B[1;32m${formula}\x1B[0m to the world? [y/N] "
        read answer
        [[ $answer =~ ^[Yy]$ ]] && add $formula
    done
    return 0
}

destroy() {
    rm -f $WORLD
}

help() {
  echo 'Example Usage:'
  echo '  brew world install FORMULA...'
  echo '  brew world uninstall FORMULA...'
  echo '  brew world list'
  echo '  brew world add FORMULA...'
  echo '  brew world delete FORMULA...'
  echo '  brew world clean'
  echo '  brew world destroy'
  echo '  brew world help'
}

error() {
    echo -e "\x1B[31mError:\x1B[0m $1" >&2
    return 1
}

[ ! -f $WORLD ] && touch $WORLD

case $1 in
    list)
        list ;;
    add)
        add "${@:2}" ;;
    delete)
        delete "${@:2}" ;;
    install)
        install "${@:2}" ;;
    uninstall|rm|remove)
        uninstall "${@:2}" ;;
    clean)
        clean ;;
    create)
        create ;;
    destroy)
        destroy ;;
    help|'')
        help ;;
    *)
        error "Unknown command: $1" ;;
esac
